{"name": "创建用户", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../api/wework.yaml'", "trace": "self = <WechatAPI.testcase.test_work.TestWework object at 0x000001F1157617B8>\n\n    @allure.title(\"创建用户\")\n    def test_create_work(self):\n>       print(Wework().test_creat_member(\"qw123\",\"测试\",\"13244433333\"))\n\nWechatAPI\\testcase\\test_work.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <WechatAPI.api.we_work.Wework object at 0x000001F1157BDA90>\n\n    def __init__(self):\n        self.token = Util().token() #不要忘了Util的()\n        self.params[\"token\"]=self.token #要记得替换token的变量\n    \n>       with open(\"../api/wework.yaml\",encoding=\"utf-8\")as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../api/wework.yaml'\n\nWechatAPI\\api\\we_work.py:27: FileNotFoundError"}, "start": 1647486668107, "stop": 1647486668612, "uuid": "d7a1d091-8d16-4e37-9b5c-5c198ace1e9f", "historyId": "62711847c1b433c1f9626da4a15aa350", "testCaseId": "9073fbec45928f38733e910e1608fcd6", "fullName": "WechatAPI.testcase.test_work.TestWework#test_create_work", "labels": [{"name": "parentSuite", "value": "WechatAPI.testcase"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestWework"}, {"name": "host", "value": "ZXJ"}, {"name": "thread", "value": "58484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "WechatAPI.testcase.test_work"}]}